# Generated by Django 5.2.12 on 2026-03-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="filename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="파일명"
            ),
        ),
        migrations.AddField(
            model_name="posts",
            name="original_filename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="원본 파일명"
            ),
        ),
    ]
